### ISSUE TITLE
Can't install on Ubuntu 18, Python 3.7, Numpy 1.16.0

### ISSUE THREAD

**Issue by ruslankotl** [CambridgeMolecularEngineering/tabledataextractor#47]
Attempting to install using `pip install git+https://github.com/CambridgeMolecularEngineering/tabledataextractor` gave the following error:

`Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/CambridgeMolecularEngineering/tabledataextractor
  Cloning https://github.com/CambridgeMolecularEngineering/tabledataextractor to /tmp/pip-req-build-jVeMk5
  Running command git clone -q https://github.com/CambridgeMolecularEngineering/tabledataextractor /tmp/pip-req-build-jVeMk5
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-jVeMk5/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-jVeMk5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-RuGpbh
         cwd: /tmp/pip-req-build-jVeMk5/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-jVeMk5/setup.py", line 11, in <module>
        long_description=open('README.md', 'r', encoding='utf-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

The machine I am running on has Ubuntu 18.04.6 as operating system.

Please advise on how to fix it.

Best wishes

Ruslan

**Comment by cjcourt** [comment]
Hi @ruslankotl, thanks for raising this issue. I am unable to replicate your issue. This error is usually associated with using python 2.x instead of python3. Can you re-confirm that you see this error when running `python3 -m pip install git+https://github.com/CambridgeMolecularEngineering/tabledataextractor`?
